services:
  - type: web
    name: cheongnyamri-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
